# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
permalink: /blog/:year/:month/:day/:title/
relative_permalinks: false
encoding: utf-8

# Setup
title:               Hello. I'm Abhishek Kumar
#tagline:             'foo's website
description:         This is my personal Blog/Portfolio
url: https://vibrantabhi19.github.io
baseurl: ""
urlimg: https://vibrantabhi19.github.io/images/
markdown: kramdown
paginate: 5
paginate_path: "/blog/page:num"
excerpt_separator: 
default_bg: sitebg.jpg
default_logo: sitelogo.png
safe: false
#timezone:    America/Chicago
future:      true


## code highlight options
syntax_highlighter: rouge
input: GFM

gems:
  - jekyll-paginate
  - jemoji
  - font-awesome-sass
  - kramdown
  - rouge
  - jekyll-mentions

jekyll-mentions:
  base_url: https://twitter.com

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "rakefile", "README.md", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "LICENSE", "vendor", "assets", "_plugins", "public/dormant"]

# About/contact
author:
  name:              Abhishek Kumar
  url:               https://twitter.com/abhi_kumar07
  avatar:         avatar.jpg
  email:           vibrantabhi19@gmail.com

# Owner/author information
owner:
  name:           Abhishek Kumar
  avatar:         avatar.jpg
  #email:          
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:
  # Social networking links used in footer. Update and remove as you like.
  twitter:        abhi_kumar07/
  facebook:       https://www.facebook.com/vibrantabhi
  github:         https://github.com/vibrantabhi19 
  linkedin:       https://www.linkedin.com/in/abhishek-kumar-74299887
  instagram:      https://www.instagram.com/abhishektiwari07/
  google_plus:    https://plus.google.com/+AbhishekKumarTiwari07
  # orcid and google scholar IDs are different than standard username.
  orcid: xyz123abc
  gscholar: xyz123abc

## sidebar links:
# For external links add external: true
links:
  - title: <i class="iconside iconm-home"></i> Home
    url: /
  - title: <i class="iconside iconm-user"></i> About
    url: /about/
  - title: <i class="iconside iconm-quill"></i> Blog
    url: /blog/
  - title: <i class="fa fa-tags"></i> Tags
    url: /tags/
  - title: <i class="fa fa-archive"></i> Archive
    url: /archive/
    external: true
  - title: <i class="iconside iconm-envelop"></i> Contact
    url: /contact/
  - title: <i class="iconside iconm-twitter"></i> Follow me on
    url: https://twitter.com/abhi_kumar07
    external: true
  - title: <i class="iconside iconm-feed2"></i> Feed
    url: /feed.xml

# Google Custom Search:
#google_search: xyz123abc

# Twitter stream widget:
# Replace xyz123abc with your twitter widget id from https://twitter.com/settings/widgets

twitter_widget_id: abhi_kumar07

# Add disqus username for Disqus comment board:
disqus_shortname: disqus_QKNhMpQgvs

# Analytics and webmaster tools stuff goes here
#google_analytics:   xyz123abc

# Enable Super-Search.
super_search: true

#### For dummy website only - remove if you wish ####
github_repo: https://github.com/vibrantabhi19
version: 1.1.1
## END ##
